export const CARRIER_CREATION = 'CARRIER_CREATION';
export const USER_CARRIER_PROFILE_CREATION = 'USER_CARRIER_PROFILE_CREATION';
export const CARRIER_PROFILE_CREATION = 'CARRIER_PROFILE_CREATION';

export const SIP_GATEWAY_CREATION = 'SIP_GATEWAY_CREATION';
export const SIP_ROUTING_CREATION = 'SIP_ROUTING_CREATION';

export const TOPUP_CAPABILITY_ACTIVATION = 'TOPUP_CAPABILITY_ACTIVATION';
export const PUSH_CAPABILITY_ACTIVATION = 'PUSH_CAPABILITY_ACTIVATION';
export const ONNET_CAPABILITY_ACTIVATION = 'ONNET_CAPABILITY_ACTIVATION';
export const OFFNET_CAPABILITY_ACTIVATION = 'OFFNET_CAPABILITY_ACTIVATION';
export const IM_CAPABILITY_ACTIVATION = 'IM_CAPABILITY_ACTIVATION';
export const VOICE_CAPABILITY_ACTIVATION = 'VOICE_CAPABILITY_ACTIVATION';
export const SMS_CAPABILITY_ACTIVATION = 'SMS_CAPABILITY_ACTIVATION';
export const API_CAPABILITY_ACTIVATION = 'API_CAPABILITY_ACTIVATION';

export const IM_TO_SMS_CAPABILITY_ACTIVATION = 'IM_TO_SMS_CAPABILITY_ACTIVATION';
export const VERIFICATION_PROFILE_CREATION = 'VERIFICATION_PROFILE_CREATION';

export const NOTIFICATION_CREATION = 'NOTIFICATION_CREATION';

export const BOSS_PROVISION = 'BOSS_PROVISION';

export const FEATURE_SET_CREATION = 'FEATURE_SET_CREATION';
export const SAVE_APPLICATION = 'SAVE_APPLICATION';
export const CERTIFICATION_CREATION = 'CERTIFICATION_CREATION';

export const COMPANY_CREATION = 'COMPANY_CREATION';
export const WLP_ACCESS_CREATION = 'WLP_ACCESS_CREATION';
export const SIGN_UP_RULE_PROVISION = 'SIGN_UP_RULE_PROVISION';

export const SMS_REALM_CREATION = 'SMS_REALM_CREATION';
export const SMS_SERVICE_PLAN_CREATION = 'SMS_SERVICE_PLAN_CREATION';

export const PARALLEL_ALL_START = 'PARALLEL_ALL_START';
export const JOIN_CAPABILITY_AND_FEATURE_SET = 'JOIN_CAPABILITY_AND_FEATURE_SET';
export const PARALLEL_ALL_END = 'PARALLEL_ALL_END';

export const PROVISIONING_START = 'PROVISIONING_START';
export const PROVISIONING_END = 'PROVISIONING_END';

export const DEFAULT_EVENT_HANDLER = 'defaultEventHandler';
export const DEFAULT_ERROR_HANDLER = 'defaultErrorHandler';
