swagger: '2.0'
host: 'deploy.dev.maaii.com:4005'
info:
  version: '1.1.0'
  title: MPS (Maaii Provisioning Service)
  description: >
    MPS enables automation of service provisioning offered by Maaii / M800.
paths:
  /provisioning:
    get:
      summary: Find provisionings
      operationId: getProvisionings
      tags:
        - Provisioning
      produces:
        - application/json
      parameters:
        - name: provisioningId
          in: query
          description: provisioning ids to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: status
          in: query
          description: process statuses to filter by
          required: false
          type: array
          items:
            type: string
            enum:
              - CREATED
              - IN_PROGRESS
              - UPDATING
              - COMPLETE
              - ERROR
          collectionFormat: csv
        - name: profile.companyId
          in: query
          description: company ids to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: profile.serviceType
          in: query
          description: service types to filter by
          required: false
          type: array
          items:
            type: string
            enum:
              - SDK
              - WHITE_LABEL
              - LIVE_CONNECT
          collectionFormat: csv
        - name: profile.companyCode
          in: query
          description: company codes to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: profile.carrierId
          in: query
          description: carrier ids to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: profile.resellerCarrierId
          in: query
          description: reseller carrier ids to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: profile.resellerCompanyId
          in: query
          description: reseller company ids to filter by
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: search
          in: query
          description: company code to search by
          required: false
          type: string
        - name: page
          in: query
          description: one-based page number
          required: false
          default: 1
          minimum: 1
          type: number
          format: int32
        - name: pageSize
          in: query
          description: number of items per page
          required: false
          default: 10
          maximum: 500
          type: number
          format: int32
      responses:
        '200':
          description: page of provisionings
          schema:
            allOf:
              - $ref: "#/definitions/PageMeta"
              - type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/definitions/ProvisioningWithMeta"
        default:
          description: any error
          schema:
            $ref: "#/definitions/ErrorWrapper"
    post:
      summary: Start a new provisioning
      operationId: createProvisioning
      tags:
        - Provisioning
      parameters:
        - name: provisioningProfile
          in: body
          required: true
          schema:
            $ref: "#/definitions/ProvisioningProfile"
      responses:
        '200':
          description: created provisioning
          schema:
            $ref: "#/definitions/ProvisioningWithMeta"
        '422':
          description: validation error
          schema:
            $ref: "#/definitions/ValidationErrorWrapper"
        default:
          description: any error
          schema:
            $ref: "#/definitions/ErrorWrapper"
  /provisioning/{provisioningId}:
    get:
      summary: Find provisioning by id
      operationId: getProvisioningById
      tags:
        - Provisioning
      parameters:
        - name: provisioningId
          type: string
          in: path
          required: true
      responses:
        '200':
          description: existing provisioning
          schema:
            $ref: "#/definitions/ProvisioningWithMeta"
        default:
          description: any error
          schema:
            $ref: "#/definitions/ErrorWrapper"
    put:
      summary: Update provisioning
      operationId: updateProvisioning
      tags:
        - Provisioning
      parameters:
        - name: provisioningId
          type: string
          in: path
          required: true
        - name: provisioningUpdate
          in: body
          required: true
          schema:
            $ref: "#/definitions/ProvisioningUpdate"
      responses:
        '200':
          description: updated provisioning
          schema:
            $ref: "#/definitions/ProvisioningWithMeta"
        '422':
          description: validation error
          schema:
            $ref: "#/definitions/ValidationErrorWrapper"
        default:
          description: any error
          schema:
            $ref: "#/definitions/ErrorWrapper"
  /preset/{presetId}:
    get:
      summary: Get preset
      operationId: getPreset
      tags:
        - Preset
      parameters:
        - name: presetId
          type: string
          in: path
          required: true
      responses:
        '200':
          description: existing preset
          schema:
            $ref: "#/definitions/ProvisioningPreset"
        default:
          description: any error
          schema:
            $ref: "#/definitions/ErrorWrapper"
    post:
      summary: Set preset
      operationId: setPreset
      tags:
        - Preset
      parameters:
        - name: presetId
          type: string
          in: path
          required: true
        - name: preset
          in: body
          required: true
          schema:
            $ref: "#/definitions/ProvisioningPreset"
      responses:
        '200':
          description: updated preset
          schema:
            $ref: "#/definitions/ProvisioningPreset"
        '422':
          description: validation error
          schema:
            $ref: "#/definitions/ValidationErrorWrapper"
        default:
          description: any error
          schema:
            $ref: "#/definitions/ErrorWrapper"
definitions:
  ProvisioningWithMeta:
    allOf:
      - $ref: "#/definitions/Provisioning"
      - $ref: "#/definitions/TimestampMeta"
  Provisioning:
    type: object
    required:
      - id
      - status
      - profile
    properties:
      id:
        type: string
      status:
        $ref: "#/definitions/ProvisioningStatus"
      profile:
        $ref: "#/definitions/ProvisioningProfile"
      finishAt:
        type: string
        format: dateTime
      taskErrors:
        type: array
        items:
          $ref: "#/definitions/ProvisioningError"
      taskResults:
        $ref: "#/definitions/ProvisioningResult"
  ProvisioningUpdate:
    type: object
    required:
      - profile
    properties:
      profile:
        $ref: "#/definitions/ProvisioningProfile"
  ProvisioningProfile:
    allOf:
      - $ref: "#/definitions/ProvisioningPreset"
      - type: object
        required:
          - companyCode
          - country
          - resellerCompanyId
          - resellerCarrierId
        properties:
          companyInfo:
            $ref: "#/definitions/CompanyInfo"
          companyCode:
            type: string
          country:
            type: string
          resellerCompanyId:
            type: string
          resellerCarrierId:
            type: string
          smsc:
            $ref: "#/definitions/SmscOptions"
  ProvisioningPreset:
    type: object
    required:
      - serviceType
      - paymentMode
      - chargeWallet
    properties:
      capabilities:
        type: array
        uniqueItems: true
        items:
          $ref: "#/definitions/Capability"
      serviceType:
        $ref: "#/definitions/ServiceType"
      paymentMode:
         $ref: "#/definitions/PaymentMode"
      chargeWallet:
        $ref: "#/definitions/ChargeWalletType"
      billing:
        $ref: "#/definitions/BillingOptions"
      smsc:
        $ref: "#/definitions/SmscOptions"
  ProvisioningResult:
    type: object
    properties:
      adminRoleCreated:
        type: boolean
      developerId:
        type: string
      bossProvisionId:
        type: string
      carrierId:
        type: string
        example: 'carrier.maaii.org'
      carrierProfileId:
        type: string
      certificates:
        type: array
        items:
          type: object
          properties:
            certificateId:
              type: string
            templateId:
              type: string
      certificatesCreated:
        type: boolean
      companyId:
        type: string
      capabilities:
        type: array
        items:
          $ref: '#/definitions/Capability'
      featureSetId:
        type: string
      featureSetIdentifier:
        type: string
      smsProfileId:
        type: string
      signUpRuleIds:
        type: array
        items:
          type: string
      notifications:
        type: array
        items:
          type: string
      notificationsCreated:
        type: boolean
      applicationIdentifier:
        type: string
      applications:
        type: array
        items:
          type: object
          properties:
            app:
              type: object
            platform:
              type: string
              enum:
                - platform.ios
                - platform.android
      sipGateways:
        type: array
        items:
          type: string
      sipRoutingProfileId:
        type: string
      userCarrierProfileId:
        type: string
      verificationProfileId:
        type: string
      voiceProfileId:
        type: string
      smsRealmId:
        type: string
      smsServicePlanId:
        type: string
  ProvisioningError:
    type: object
    description: user or system errors during provisioning process
    required:
      - message
      - name
    properties:
      message:
        type: string
        description: error message in english
      name:
        $ref: '#/definitions/ProvisioningErrorType'
      traceId:
        type: string
        description: trace id associated with the error
        example: NOTIFICATION_CREATION:a17a4306-77b2-4c09-a7c8-9e9dddb8fba7
      eventName:
        type: string
        description: associated event name
        example: NOTIFICATION_CREATION
  ProvisioningErrorType:
    type: string
    description: error code / type
    enum:
      - SystemError
  CompanyInfo:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      description:
        type: string
      timezone:
        type: string
      contact:
        type: string
  SmscOptions:
    type: object
    required:
      - needBilling
      - sourceAddress
    properties:
      needBilling:
        type: boolean
      defaultRealm:
        type: string
      servicePlanId:
        type: string
      sourceAddress:
        type: string
      realm:
        $ref: "#/definitions/Realm"
  Realm:
    type: object
    required:
    - systemId
    - password
    - bindingDetails
    properties:
      systemId:
        type: string
      password:
        type: string
      bindingDetails:
        type: array
        items:
          $ref: '#/definitions/BindingDetail'
        x-array-min-size: 1
        description: user must have one or more binding details
  BindingDetail:
    type: object
    required:
    - ip
    - port
    properties:
      ip:
        type: string
      port:
        type: number
        format: int32
  BillingOptions:
    type: object
    required:
      - currency
    properties:
      smsPackageId:
        type: number
        format: int32
      offnetPackageId:
        type: number
        format: int32
      currency:
        $ref: "#/definitions/Currency"
  Currency:
    type: number
    description: currency code
  ProvisioningStatus:
    type: string
    enum:
      - CREATED
      - IN_PROGRESS
      - UPDATING
      - COMPLETE
      - ERROR
  ChargeWalletType:
    type: string
    enum:
      - WALLET_NONE
      - WALLET_END_USER
      - WALLET_COMPANY
      - WALLET_OCS_INTEGRATION
  PaymentMode:
    type: string
    enum:
      - PRE_PAID
      - POST-PAID
  ServiceType:
    type: string
    enum:
      - SDK
      - WHITE_LABEL
      - LIVE_CONNECT
  Capability:
    type: string
    enum:
      - im
      - im.im-to-sms
      - call.onnet
      - call.offnet
      - call.maaii-in
      - push
      - verification.mo
      - verification.mt
      - verification.sms
      - verification.ivr
      - vsf
      - platform.android
      - platform.ios
      - platform.web
      - end-user.whitelist
      - end-user.suspension
  # Share this definitions accross services?
  ErrorWrapper:
    type: object
    required:
      - error
    properties:
      error:
        $ref: '#/definitions/Error'
  ValidationErrorWrapper:
    type: object
    required:
      - error
    properties:
      error:
        $ref: '#/definitions/ValidationError'
  Error:
    type: object
    required:
      - message
      - name
      - status
    properties:
      message:
        type: string
      name:
        type: string
      code:
        type: number
        format: int32
      status:
        type: number
        format: int32
        example: 404
  ValidationError:
    allOf:
      - $ref: '#/definitions/Error'
      - type: object
        properties:
          details:
            type: array
            items:
              $ref: '#/definitions/ValidationErrorDetail'
  ValidationErrorDetail:
    type: object
    required:
      - message
      - path
    properties:
      message:
        type: string
      path:
        type: string
        example: 'nested.field'
      type:
        type: string
        example: 'string.min'
  PageMeta:
    type: object
    properties:
      page:
        description: one-based page number
        type: number
        format: int32
        minimum: 1
      pageSize:
        description: number of items per page
        type: number
        format: int32
        maximum: 500
      pageTotal:
        description: total number of pages
        type: number
        format: int32
      total:
        description: total number of items
        type: number
        format: int32
  TimestampMeta:
    type: object
    properties:
      createdAt:
        type: string
        format: dateTime
      updatedAt:
        type: string
        format: dateTime
