import Joi from 'joi';

const PUBLIC_ERROR_SCHEMA = Joi.object({
  message: Joi.string().required(),
  name: Joi.string().default('SystemError').required(),
  code: Joi.string(),
  path: Joi.string(),
  traceId: Joi.string(),
  eventName: Joi.string(),
}).options({ allowUnknown: true });

export const PUBLIC_STATE_SCHEMA = Joi.object({
  results: Joi.object({
    adminRoleCreated: Joi.boolean(),
    applicationIdentifier: Joi.string().allow(null),
    applications: Joi.array(Joi.object({
      app: Joi.object().required(),
      platform: Joi.string().required(),
    })),
    bossProvisionId: Joi.string().allow(null),
    capabilities: Joi.array().items(Joi.string()),
    carrierId: Joi.string().allow(null),
    carrierProfileId: Joi.string().allow(null),
    certificates: Joi.array(Joi.object({
      certificateId: Joi.string().required(),
      templateId: Joi.string().required(),
    })),
    certificatesCreated: Joi.boolean(),
    companyId: Joi.string().allow(null),
    developerId: Joi.string().allow(null),
    featureSetId: Joi.string().allow(null),
    featureSetIdentifier: Joi.string().allow(null),
    notifications: Joi.array().items(Joi.string()),
    notificationsCreated: Joi.boolean(),
    offnetChargingRateId: Joi.string().allow(null),
    signUpRuleIds: Joi.array().items(Joi.string()),
    sipGateways: Joi.array(Joi.string()),
    sipRoutingProfileId: Joi.string().allow(null),
    smsChargingRateId: Joi.string().allow(null),
    smsProfileId: Joi.string().allow(null),
    smsRealmId: Joi.string().allow(null),
    smsServicePlanId: Joi.string().allow(null),
    userCarrierProfileId: Joi.string().allow(null),
    verificationProfileId: Joi.string().allow(null),
    voiceProfileId: Joi.string().allow(null),
  }).options({ presence: 'required' }),
  errors: Joi.array().items(PUBLIC_ERROR_SCHEMA),
});

export const DEFAULT_PUBLIC_STATE = {
  adminRoleCreated: false,
  applicationIdentifier: null,
  applications: [],
  bossProvisionId: null,
  capabilities: [],
  carrierId: null,
  carrierProfileId: null,
  certificates: [],
  certificatesCreated: false,
  companyId: null,
  developerId: null,
  featureSetId: null,
  featureSetIdentifier: null,
  notifications: [],
  notificationsCreated: false,
  offnetChargingRateId: null,
  signUpRuleIds: [],
  sipGateways: [],
  sipRoutingProfileId: null,
  smsChargingRateId: null,
  smsProfileId: null,
  smsRealmId: null,
  smsServicePlanId: null,
  userCarrierProfileId: null,
  verificationProfileId: null,
  voiceProfileId: null,
};
